"""Initial agent package for the local LLM runtime prototype."""

from .llm_client import (
    LocalLLMClient,
    LocalLLMClientError,
    LocalLLMJSONError,
    LocalLLMRequestError,
    LocalLLMResponseError,
    LocalLLMValidationError,
)
from .agent import Agent, AgentStepRequest, AgentStepResult
from .orchestrator import Orchestrator
from .prompt_contract import (
    NEXT_ACTION_JSON_SCHEMA_TEXT,
    PROMPT_CONTRACT_ID,
    PromptBuilder,
    PromptContractConfig,
    PromptMessages,
)
from .recovery import (
    FailureEvent,
    RecoveryDecision,
    RecoveryPolicy,
    RecoveryPolicyConfig,
    RecoveryPolicyRule,
    default_recovery_policy,
    failure_event_from_exception,
    load_recovery_policy,
)
from .script_runner_errors import (
    NormalizedScriptError,
    NormalizedScriptResult,
    is_retryable_category,
    normalize_error_type,
    normalize_many_script_results,
    normalize_script_exception,
    normalize_script_execution_result,
    recovery_category_for_script_error,
    severity_for_category,
)
from .role_template import (
    RoleActivityScenario,
    RoleConstraintProfile,
    RoleResourceProfile,
    RoleTemplate,
    load_role_template,
    role_template_to_agent_state_defaults,
)
from .action_validation_cases import (
    ActionValidationCaseSuite,
    ActionValidationExpectedOutcome,
    ActionValidationTestCase,
    cases_by_tag,
    load_action_validation_cases,
    probe_next_action_contract,
    summarize_cases,
)
from .action_selector import (
    ActionSelectionResult,
    ActionSelector,
    ActionSelectorConfig,
    load_action_selector_config,
)
from .schemas import (
    AgentContractConfig,
    HardwareConfig,
    LoggingConfig,
    ModelConfig,
    NextAction,
    ProjectRuntimeConfig,
    RuntimeConfig,
)
from .state import (
    ActionHistoryEntry,
    ActionSpec,
    AgentConstraints,
    AgentEnvironment,
    AgentObjective,
    AgentResources,
    AgentRole,
    AgentState,
    load_agent_state,
)

__all__ = [
    "ActionHistoryEntry",
    "ActionSpec",
    "ActionValidationCaseSuite",
    "ActionValidationExpectedOutcome",
    "ActionValidationTestCase",
    "ActionSelectionResult",
    "ActionSelector",
    "ActionSelectorConfig",
    "Agent",
    "AgentContractConfig",
    "AgentConstraints",
    "AgentEnvironment",
    "AgentObjective",
    "AgentResources",
    "AgentRole",
    "AgentState",
    "AgentStepRequest",
    "AgentStepResult",
    "HardwareConfig",
    "LocalLLMClient",
    "LocalLLMClientError",
    "LocalLLMJSONError",
    "LocalLLMRequestError",
    "LocalLLMResponseError",
    "LocalLLMValidationError",
    "LoggingConfig",
    "ModelConfig",
    "NextAction",
    "NormalizedScriptError",
    "NormalizedScriptResult",
    "Orchestrator",
    "ProjectRuntimeConfig",
    "PROMPT_CONTRACT_ID",
    "NEXT_ACTION_JSON_SCHEMA_TEXT",
    "PromptBuilder",
    "PromptContractConfig",
    "PromptMessages",
    "RoleActivityScenario",
    "RoleConstraintProfile",
    "RoleResourceProfile",
    "RoleTemplate",
    "RecoveryDecision",
    "RecoveryPolicy",
    "RecoveryPolicyConfig",
    "RecoveryPolicyRule",
    "RuntimeConfig",
    "FailureEvent",
    "default_recovery_policy",
    "cases_by_tag",
    "failure_event_from_exception",
    "load_agent_state",
    "load_action_validation_cases",
    "load_action_selector_config",
    "load_role_template",
    "load_recovery_policy",
    "normalize_error_type",
    "normalize_many_script_results",
    "normalize_script_exception",
    "normalize_script_execution_result",
    "probe_next_action_contract",
    "recovery_category_for_script_error",
    "role_template_to_agent_state_defaults",
    "severity_for_category",
    "is_retryable_category",
    "summarize_cases",
]
